version: '3.8'

services:
  frontend:
    container_name: pingpal-frontend
    image: ritiksharma454/pingpal:frontend-v1.0
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    container_name: pingpal-backend
    image: ritiksharma454/pingpal:backend-v1.0
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: pingpal-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
